CREATE TABLE USERS (USER_ID SERIAL,
                    USER_NAME VARCHAR(100),
                    START_TS TIMESTAMP(6) DEFAULT CURRENT_TIMESTAMP NOT NULL,
                    END_TS TIMESTAMP(6)
);

ALTER TABLE USERS ADD
    CONSTRAINT PK_USERS PRIMARY KEY (USER_ID)
;

CREATE TABLE OPTIONS (OPTION_ID SERIAL,
                        QUESTION_ID BIGINT,
                        OPT_VALUE VARCHAR(4000),
                        OPT_SELECTED BOOLEAN,
                        OPT_CORRECT BOOLEAN,
                      START_TS TIMESTAMP(6) DEFAULT CURRENT_TIMESTAMP NOT NULL,
                      END_TS TIMESTAMP(6)
                     )
;

ALTER TABLE OPTIONS ADD
    CONSTRAINT PK_OPTIONS PRIMARY KEY (OPTION_ID)
;

CREATE TABLE QUESTIONS (QUESTION_ID SERIAL,
                    QUIZ_ID BIGINT,
                    QUESTION VARCHAR(4000),
                    QUESTION_NUM INTEGER,
                    START_TS TIMESTAMP(6) DEFAULT CURRENT_TIMESTAMP NOT NULL,
                    END_TS TIMESTAMP(6)
                       )
;

ALTER TABLE QUESTIONS ADD
    CONSTRAINT PK_QUESTIONS PRIMARY KEY (QUESTION_ID)
;

CREATE TABLE QUIZ (QUIZ_ID SERIAL,
                        USER_ID BIGINT,
                        QUESTIONS_TOTAL INTEGER DEFAULT 0,
                        QUESTIONS_CORRECT INTEGER DEFAULT 0,
                        TIME_TOTAL INTEGER DEFAULT 0,
                        START_TS TIMESTAMP(6) DEFAULT CURRENT_TIMESTAMP NOT NULL,
                        END_TS TIMESTAMP(6)
)
;

ALTER TABLE QUIZ ADD
    CONSTRAINT PK_QUIZ PRIMARY KEY (QUIZ_ID)
;

ALTER TABLE OPTIONS ADD CONSTRAINT FK_OPTIONS_QUESTION_ID
    FOREIGN KEY (QUESTION_ID) REFERENCES QUESTIONS(QUESTION_ID)
        ON DELETE CASCADE
;

ALTER TABLE QUESTIONS ADD CONSTRAINT FK_QUESTIONS_QUIZ_ID
    FOREIGN KEY (QUIZ_ID) REFERENCES QUIZ(QUIZ_ID)
        ON DELETE CASCADE
;

ALTER TABLE QUIZ ADD CONSTRAINT FK_QUIZ_USER_ID
    FOREIGN KEY (USER_ID) REFERENCES USERS(USER_ID)
        ON DELETE CASCADE
;

CREATE SEQUENCE hibernate_sequence START 1;