CREATE TABLE CONNECTION_STATUS (CONNECTION_STATUS_ID SERIAL,
                        USER_ID BIGINT,
                        ONLINE boolean DEFAULT true,
                        START_TS TIMESTAMP(6) DEFAULT CURRENT_TIMESTAMP NOT NULL,
                        END_TS TIMESTAMP(6)
)
;

ALTER TABLE CONNECTION_STATUS ADD
    CONSTRAINT PK_CONNECTION_STATUS PRIMARY KEY (CONNECTION_STATUS_ID)
;

ALTER TABLE CONNECTION_STATUS ADD CONSTRAINT FK_CONNECTION_STATUS_QUIZ_ID
    FOREIGN KEY (USER_ID) REFERENCES USERS(USER_ID)
        ON DELETE CASCADE
;