spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgrespw
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  flyway:
    url: jdbc:postgresql://localhost:5432/postgres
    schemas: postgres
    user: postgres
    password: postgrespw
server:
  servlet:
    context-path: /
  port: 8082